language: python
python:
  - '3.7'
before_install: 
 - sudo apt-get install libboost-dev libboost-test-dev doxygen graphviz
install:
  - pip install pipenv
  - pipenv install
script: 
  - python DeepPanel.py